name: website
description: "Habit tracker"
publish_to: 'none'
version: 1.1.0

environment:
  sdk: ^3.5.4
  flutter: ^3.24.5

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.1
  http: ^0.13.3
  cupertino_icons: ^1.0.8
  requests: ^4.7.0
  pair: ^0.1.2
  bcrypt: ^1.1.3
  crypto: ^3.0.1
  tuple: ^2.0.0
  fl_chart: ^0.65.0
  logger: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - web/icons/.
    - web/icons/navigations/.
